# 🔱 CHORUS Development Overrides (Simple & Correct)
# Overrides the base services for local development.
services:
  chorus-web:
    build:
      target: builder
    image: chorus-app-builder:latest
    volumes:
      - .:/app
    command: ["uv", "run", "gunicorn", "--bind", "0.0.0.0:5001", "--workers", "2", "--reload", "chorus_engine.infrastructure.web.web_ui:app"]

  chorus-launcher:
    build:
      target: builder
    image: chorus-app-builder:latest
    volumes:
      - .:/app

  chorus-sentinel:
    build:
      target: builder
    image: chorus-app-builder:latest
    volumes:
      - .:/app

  chorus-stream-processor:
    build:
      target: builder
    image: chorus-app-builder:latest
    volumes:
      - .:/app

  chorus-tester:
    build:
      target: builder
    image: chorus-app-builder:latest
    volumes:
      - .:/app
